typography_spectrum: 0.969534
color:
  saturation: 0.7222222
  brandStrength: 0.1071106
  lightness: 0.3100359
  rhythmicContrast: 0.6630824
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.9784946
name: Theviolentuniverse
title: The Violent Universe
